### PR TITLE
bump semver version

### PR DESCRIPTION
**Pull request by steveklabnik**
This will help crates.io eventually: https://github.com/rust-lang/crates.io/pull/458

### CODE REVIEW

**Comment by steveklabnik** [comment]
I've also bumped the version of conduit itself, just in case. lemme know if that's not a good idea.

**Comment by steveklabnik** [comment]
Actually, let me update ALL the conduit crates in unison here...

**Comment by steveklabnik** [comment]
Ah, so it looks like they all depend on this crate, so I can't upgrade them until this upgrade goes through.

**Comment by alexcrichton** [comment]
👍

**Comment by steveklabnik** [comment]
:metal: :heart:

**Comment by steveklabnik** [comment]
(oh and if you could cut a release outta this at some point that'd be rad as well)

**Comment by alexcrichton** [comment]
Done!

**Pull request merged**
